### ISSUE TITLE
Spacing on Headings

### ISSUE THREAD

**Issue by alexanderkuenzel** [docmost/docmost#1470]
Hi, i think it would look much better and also give a better structure if the spacing after a heading is smaller then the spacing before the heading.

### Currently there is exact the same spacing before and after a heading.
<img width="100%" alt="Image" src="https://github.com/user-attachments/assets/5a790e8f-5128-4f27-a0e7-06ed0f44467b" />

### If there is less space after the heading, it looks better and the structure ist more clear.
<img width="100%" alt="Image" src="https://github.com/user-attachments/assets/661605fa-7052-489b-b7a5-67f8917fb5a4" />

What do you think about this?

Greetings
Alex

**Comment by Eshwar1212-maker** [comment]
@alexanderkuenzel Hey can you assign this to me? New to docmost and think this can be a good first issue. 
But I am not sure if the maintainer would approve of it. Its his design choice.

**Comment by ReessKennedy** [comment]
I just threw an override in my custom CSS chrome extension and worked right away, without needing integration in core -- or use Clouflare to insert it across your entire app for everyone on your team. 

```
.mantine-AppShell-main .mantine-Container-root h2 {
	margin-bottom: 10px !important;
}
.mantine-AppShell-main .mantine-Container-root h3 {
	margin-bottom: 10px !important;
}
.mantine-AppShell-main .mantine-Container-root h4 {
	margin-bottom: 10px !important;
}
```

**Comment by Philipinho** [comment]
Fixed here https://github.com/docmost/docmost/commit/adec36d5449f8cb5dd068389d2e5c86e027b4906.

**Comment by alexanderkuenzel** [comment]
The spacing got smaller, but it's still the same spacing at top and bottom of a heading. The spacing on top should be bigger than the spacing on bottom.

**Comment by Philipinho** [comment]
Fixed in in v0.70. 
@alexanderkuenzel feel free to comment if you have any feedback.
