### ISSUE TITLE
Coloring bulletin in the same section is not working properly

### ISSUE THREAD

**Issue by manjurksa** [docmost/docmost#867]
Coloring bulletin in the same section is not working properly.

https://github.com/user-attachments/assets/2c4d94fb-ee84-4cc4-a62a-c46a8127ecf5

**Comment by savvy-bit** [comment]
I guess this has been already fixed.

**Comment by manjurksa** [comment]
Has it? I can still reproduce it with 0.8.4. It only happens with bulletins.

**Comment by savvy-bit** [comment]
![Image](https://github.com/user-attachments/assets/ba6112d1-2212-44df-a329-e8efa59e59d6)

This is what happens with the latest code. It is working fine now.

**Comment by ai-crossroads** [comment]
I still have this issue for v0.8.4
